defaults:
  - maniskill_base  
  - _self_            

name: maniskill_stack

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud

env_runner:
  _target_: diffusion_policy_3d.env_runner.maniskill_runner.ManiSkillRunner
  task_name: StackFr3Env-v1
  robot_uids: "fr3_umi"
  cam_name: "right_cam"
  num_points: 1024

dataset:
  _target_: diffusion_policy_3d.dataset.maniskill_dataset.ManiSkillDataset
  zarr_path: /home/max/projects/gsplat_policy/datasets/3d_diffusion_policy/stack
